services:

  mongo:
    container_name: mongo
    image: mongo
    env_file:
      - .env 
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=${MONGODB_ADMINUSERNAME}
    #   - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ADMINPASSWORD}
    #   - MONGO_INITDB_DATABASE=${DATABASE_NAME}
    volumes:
      - shared-data:/shared
    ports:
      - "${MONGODB_PORT}:27017"
    networks:
      - server-net
    deploy:
      resources:
        limits:
          cpus: '0.5'  
          memory: 512M  
        reservations:
          cpus: '0.25'  
          memory: 256M   

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      # Optional - if you have authentication enabled:
      # ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_ADMINUSERNAME}
      # ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_ADMINPASSWORD}
      # ME_CONFIG_MONGODB_AUTH_DATABASE: admin
    ports:
      - "8081:8081"
    networks:
      - server-net
    depends_on:
      - mongo


  # nginx:
  #   build:
  #     context: .
  #     dockerfile: ./Docker/Dockerfile.nginx
  #   ports:
  #     - "80:80"
  #   env_file:
  #     - .env
  #   depends_on:
  #     - application
  #     - application2
  #     - application3
  #   networks:
  #     - server-net
  #   # volumes:
  #   #   - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.5'
  #         memory: 512M 
  #       reservations:
  #         cpus: '0.25'
  #         memory: 256M

  # application:
  #   build:
  #     context: .
  #     dockerfile: ./Docker/Dockerfile
  #   container_name: application
  #   hostname: application
  #   env_file:
  #     - .env
  #   volumes:
  #     - shared-data:/shared
  #   # ports:
  #   #   - "1111:${PORT}"
  #   networks:
  #     - server-net
  #   depends_on:
  #     - mongo
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.5'
  #         memory: 512M 
  #       reservations:
  #         cpus: '0.25'
  #         memory: 256M 

  # application2:
  #   build:
  #     context: .
  #     dockerfile: ./Docker/Dockerfile
  #   container_name: application2
  #   hostname: application2
  #   env_file:
  #     - .env
  #   volumes:
  #     - shared-data:/shared
  #   # ports:
  #   #   - "2222:${PORT}"
  #   networks:
  #     - server-net
  #   depends_on:
  #     - mongo
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.5'
  #         memory: 512M   
  #       reservations:
  #         cpus: '0.25'  
  #         memory: 256M 

  # application3:
  #   build:
  #     context: .
  #     dockerfile: ./Docker/Dockerfile
  #   container_name: application3
  #   hostname: application3
  #   env_file:
  #     - .env
  #   volumes:
  #     - shared-data:/shared
  #   # ports:
  #   #   - "3333:${PORT}"
  #   networks:
  #     - server-net
  #   depends_on:
  #     - mongo
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.5' 
  #         memory: 512M
  #       reservations:
  #         cpus: '0.25' 
  #         memory: 256M 

networks:
  server-net:

volumes:
  shared-data: