export const PAYMENT_STATUS = {
    PENDING: "PENDING",
    COMPLETED: "COMPLETED",
    FAILED: "FAILED",
    CANCELLED: "CANCELLED",
    REFUNDED: "REFUNDED",
    PAYED: "PAID",
    PROVIDER_CANCELLED: "PROVIDER_CANCELLED",
};