export enum PAYMENT_STATUS {
    PENDING = "PENDING",
    COMPLETED = "COMPLETED",
    FAILED = "FAILED",
    CANCELLED = "CANCELLED",
    REFUNDED = "REFUNDED",
    PAID = "PAID",
    PROVIDER_CANCELLED = "PROVIDER_CANCELLED",
};