export enum USER_ROLES {
  ADMIN = 'ADMIN',
  CLIENT = 'CLIENT',
  PROVIDER = 'PROVIDER'
}

export enum STATUS {
  ACTIVE = 'ACTIVE',
  DELETED = 'DELETED',
  BLOCKED = 'BLOCKED'
}

export enum GENDER {
  MALE = 'Male',
  FEMALE = 'Female',
  OTHERS = 'Others'
}

export enum VERIFICATION_STATUS {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  UNVERIFIED = 'UNVERIFIED'
}